# This file was generated by GoReleaser. DO NOT EDIT.
class EcsServiceLogs < Formula
  desc "ecs-service-logs is used to filter JSON-formatted log lines in CloudWatch."
  homepage "https://github.com/trussworks/ecs-service-logs"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trussworks/ecs-service-logs/releases/download/v0.3.0/ecs-service-logs_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "c829232f54e72c2a9ebebc4b504fd65eb9b3f1e1ef199f940527e2a8943d9bfd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/ecs-service-logs/releases/download/v0.3.0/ecs-service-logs_0.3.0_Linux_x86_64.tar.gz"
      sha256 "2803177477bb917a19fc89f36f4972af740f80d35380cbe2c97345bb6d109f8e"
    end
  end

  def install
    bin.install "ecs-service-logs"
  end
end
