# This file was generated by GoReleaser. DO NOT EDIT.
class EcsServiceLogs < Formula
  desc "ecs-service-logs is used to filter JSON-formatted log lines in CloudWatch."
  homepage "https://github.com/trussworks/ecs-service-logs"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trussworks/ecs-service-logs/releases/download/v0.1.3/ecs-service-logs_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "4e912ffa671c552f9d096c5d2f5c3adf8289dd5144c4fcbe297c884733bd5ca4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/ecs-service-logs/releases/download/v0.1.3/ecs-service-logs_0.1.3_Linux_x86_64.tar.gz"
      sha256 "aa1b9d0665d2ab4541ad1245df35c4b5edf53fda8301294958eeb8acad9b40e8"
    end
  end

  def install
    bin.install "ecs-service-logs"
  end
end
