# This file was generated by GoReleaser. DO NOT EDIT.
class EcsServiceLogs < Formula
  desc "ecs-service-logs is used to filter JSON-formatted log lines in CloudWatch."
  homepage "https://github.com/trussworks/ecs-service-logs"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trussworks/ecs-service-logs/releases/download/v0.1.3/ecs-service-logs_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "b7e1c221f8e764f074c709caa894b100153606c69e9efcdc6254df40eaf48ebf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/ecs-service-logs/releases/download/v0.1.3/ecs-service-logs_0.1.3_Linux_x86_64.tar.gz"
      sha256 "a65aa2255b0e30cf45eb2d5030e27f29b466b42c6cdefe080e0beebbbfef8363"
    end
  end

  def install
    bin.install "ecs-service-logs"
  end
end
