# This file was generated by GoReleaser. DO NOT EDIT.
class FindGuarddutyUser < Formula
  desc "find-guardduty-user is used to search CloudTrial to find users that triggered GuardDuty alerts."
  homepage "https://github.com/trussworks/find-guardduty-user"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trussworks/find-guardduty-user/releases/download/v0.0.1/find-guardduty-user_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "03c7e56dd0014324082e02955bea53f29d91c04fa039df09dc23da511334b493"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/find-guardduty-user/releases/download/v0.0.1/find-guardduty-user_0.0.1_Linux_x86_64.tar.gz"
      sha256 "16ca73c9e34d7903f5541ebd99e9ad5b2a6e2f259c233a875faf7ca892d06713"
    end
  end

  def install
    bin.install "find-guardduty-user"
  end
end
