# This file was generated by GoReleaser. DO NOT EDIT.
class HealthChecker < Formula
  desc "health-checker is used to verity that websites are healthy following a deploy."
  homepage "https://github.com/trussworks/health-checker"
  version "0.0.0"

  if OS.mac?
    url "https://github.com/trussworks/health-checker/releases/download/v0.0.0/health-checker_0.0.0_Darwin_x86_64.tar.gz"
    sha256 "fb524ed55ca40e350ff5b8d93d57fcee1ea3e38ece588998c7b1fc64f434658c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/health-checker/releases/download/v0.0.0/health-checker_0.0.0_Linux_x86_64.tar.gz"
      sha256 "e7b45d7aa560d5bb27ec194efcd4b75b19b70d1a38d974eb2b40ee56cd40c33a"
    end
  end

  def install
    bin.install "health-checker"
  end
end
