# This file was generated by GoReleaser. DO NOT EDIT.
class SetupNewAwsUser < Formula
  desc "A tool that creates a virtual MFA device and rotates access keys for a new AWS user."
  homepage "https://github.com/trussworks/setup-new-aws-user"
  version "0.1.15"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trussworks/setup-new-aws-user/releases/download/v0.1.15/setup-new-aws-user_0.1.15_Darwin_x86_64.tar.gz"
    sha256 "c9235d88561d880b874e3c7dc6fc98a2565aa8c05ce74ec5d7fbc167e0ec0f9a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/setup-new-aws-user/releases/download/v0.1.15/setup-new-aws-user_0.1.15_Linux_x86_64.tar.gz"
      sha256 "481a6bc8f5004dc29226ecffba498060476f44ab78ea88f6e68665c48f40e38b"
    end
  end

  def install
    bin.install "setup-new-aws-user"
  end
end
