# This file was generated by GoReleaser. DO NOT EDIT.
class TlsChecker < Formula
  desc "tls-checker is used to verify that websites are serving on accepted TLS versions and not downgrading."
  homepage "https://github.com/trussworks/tls-checker"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trussworks/tls-checker/releases/download/v0.0.2/tls-checker_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "585c91a424f574612b50ba24ffd24100a5970e4d1108f42acfb71fc917240fc8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trussworks/tls-checker/releases/download/v0.0.2/tls-checker_0.0.2_Linux_x86_64.tar.gz"
      sha256 "a6264437889e5282c66f4e86465313498102d55f1d74f026ae9eb86160a3e086"
    end
  end

  def install
    bin.install "tls-checker"
  end
end
